# joint_limits.yaml with acceleration limits enabled
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1
joint_limits:
  left_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  left_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  left_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.0943951023931953
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
  right_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.1415926535897931
    has_acceleration_limits: true
    max_acceleration: 5.0
